version: '3'
services:
  brainspark:
    build:
      context: .
      dockerfile: ./brainspark/Dockerfile
    command: --jsonrpc --seed
    depends_on:
      - nsqd
    ports:
      - "8080:8080"
    volumes:
      - ./brainspark/config.yml:/etc/brainspark/config.yml
    environment:
      BRAINSPARK_NSQ_HOST: nsqd:4150

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"